# Generated by Django 3.2.4 on 2021-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_countdown_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='start',
            field=models.DateTimeField(blank=True, default='2021-06-21T13:02:42.539108', null=True),
        ),
    ]
