# Generated by Django 3.2.4 on 2021-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_countdown_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countdown',
            old_name='description',
            new_name='c_description',
        ),
        migrations.RenameField(
            model_name='countdown',
            old_name='end',
            new_name='c_end',
        ),
        migrations.RenameField(
            model_name='countdown',
            old_name='happening',
            new_name='c_happening',
        ),
        migrations.RenameField(
            model_name='countdown',
            old_name='status',
            new_name='c_status',
        ),
        migrations.RemoveField(
            model_name='countdown',
            name='start',
        ),
        migrations.AddField(
            model_name='countdown',
            name='c_start',
            field=models.DateTimeField(blank=True, default='2021-06-21T13:08:31.025417', null=True),
        ),
    ]
