# Generated by Django 3.2.4 on 2021-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210621_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='c_start',
            field=models.DateTimeField(blank=True, default='2021-06-21T13:08:47.790404', null=True),
        ),
    ]
