# Generated by Django 3.2.4 on 2021-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210621_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='c_start',
            field=models.DateTimeField(blank=True, default='2021-06-21T14:25:46.122932', null=True),
        ),
    ]
