# Generated by Django 3.1.3 on 2021-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_countdown_c_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdown',
            name='c_end',
        ),
        migrations.AddField(
            model_name='countdown',
            name='c_status',
            field=models.CharField(choices=[('0', 'new'), ('1', 'running'), ('2', 'done')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='c_start',
            field=models.DateTimeField(blank=True, default='2021-06-22T06:24:07.423228', null=True),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
