# Generated by Django 3.1.3 on 2021-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210622_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='c_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
