# Generated by Django 3.1.3 on 2021-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210622_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='slack_timestamp',
            field=models.CharField(default='not migrated yet', max_length=1000),
        ),
        migrations.AlterField(
            model_name='countdown',
            name='c_status',
            field=models.CharField(choices=[('New', 'new'), ('running', 'running'), ('done', 'done')], default='0', max_length=20),
        ),
    ]
