# Generated by Django 3.2.4 on 2021-06-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210623_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='c_status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('done', 'done'), ('deleting', 'deleting'), ('deleted', 'deleted')], default='0', max_length=20),
        ),
    ]
